# Generated by Django 3.2.8 on 2023-08-12 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=255)),
                ('service_type', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=255)),
                ('lastnamr', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
                ('service_name', models.CharField(max_length=255)),
                ('service_type', models.CharField(max_length=255)),
                ('comments', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=255)),
                ('support_comment', models.CharField(max_length=255)),
                ('request_raised', models.CharField(max_length=255)),
                ('request_solve', models.CharField(max_length=255)),
            ],
        ),
    ]
