# Generated by Django 3.2.8 on 2023-08-12 17:18

from django.db import migrations, models
import django.db.models.deletion
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=phone_field.models.PhoneField(blank=True, help_text='Contact phone number', max_length=31),
        ),
        migrations.AlterField(
            model_name='user',
            name='request_raised',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='request_solve',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='service_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.service'),
        ),
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('R', 'REQUEST_RCV'), ('A', 'REQ_ASSIGN'), ('P', 'PENDING'), ('S', 'SOLVE')], max_length=255),
        ),
    ]
