# Generated by Django 3.2.8 on 2023-08-13 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0006_alter_user_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='request_raised',
            field=models.DateField(null=True),
        ),
    ]
