# Generated by Django 3.2.8 on 2023-08-13 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0007_alter_user_request_raised'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='request_raised',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
