# Generated by Django 3.2.8 on 2023-08-13 03:10

from django.db import migrations, models
import django.utils.crypto


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0012_remove_user_idss'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='idss',
            field=models.CharField(default=django.utils.crypto.get_random_string, editable=False, max_length=4, unique=True),
        ),
    ]
