# Generated by Django 3.2.8 on 2023-08-13 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0013_user_idss'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='id',
        ),
        migrations.AlterField(
            model_name='user',
            name='idss',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
    ]
